services:
  db:
    container_name: plantDB
    image: postgres
    environment:
      POSTGRES_USER: sidof
      POSTGRES_PASSWORD: sidof1/@
      PGDATA: data/postgres
    ports:
      - "5332:5432"
    volumes:
      - db:/data/postgres
    networks:
      db:
    restart: unless-stopped

networks:
  db:
    driver: bridge
volumes:
  db: