#SERVER
SERVER_PORT: 8085
CONTAINER_PORT: 8085

#DATABASE
POSTGRES_USER: sidof
POSTGRES_PASSWORD: sidof1/@
POSTGRES_DATABASE: plant
POSTGRES_HOST: localhost
POSTGRES_PORT: 5332

#spring profile
ACTIVE_PROFILE: dev